name = "moz-latest-release"
workers_dev = true
compatibility_date = "2022-01-20"
account_id = "51e833a11dde67f4fb5100a8ca6fccf3"
main = "build/worker/shim.mjs"

[build]
command = "cargo install -q worker-build && worker-build --release" # required
